server:
  port: 8888
spring:
    rabbitmq:
        host: 10.12.41.89
        port: 5672
        username: lyd
        password: 123456
        virtual-host: /test
        listener:
            simple:
                acknowledge-mode: manual
canal:
    client:
        instances:
            example:
                host: localhost
                port: 11111
                batchSize: 1000

#其他配置
exchangeName: materialActivityTopicExchange
queueName: materialActivityTopicQueue
bindingKey: material.confirmed.activity

deadExchangeName: deadMaterialActivityTopicExchange
deadQueueName: deadMaterialActivityTopicQueue
deadBindingKey: material.confirmed.activity.dead